check50:
  files: &check50_files
    - !exclude "*"
    - !require hello.cpp
  checks:
    test1:
      - run: g++ hello.cpp -o hello && ./hello
        stdin: "Mohamed 24"
        stdout: "Hello Mohamed, you are 24 years old."
        exit: 0
    test2:
      - run: g++ hello.cpp -o hello && ./hello
        stdin: "Mazen 50"
        stdout: "Hello Mazen, you are 50 years old."
        exit: 0
    test3:
      - run: g++ hello.cpp -o hello && ./hello
        stdin: "John 30"
        stdout: "Hello John, you are 30 years old."
        exit: 0
    test4:
      - run: g++ hello.cpp -o hello && ./hello
        stdin: "Alice 22"
        stdout: "Hello Alice, you are 22 years old."
        exit: 0
submit50:
  files: *check50_files

