check50:
  files: &check50_files
    - !exclude "*"
    - !require average.cpp
  checks:
    test1:
      - run: g++ average.cpp -o average && ./average
        stdin: "1 2 3"
        stdout: "Average: 2.00"
    test2:
      - run: g++ average.cpp -o average && ./average
        stdin: "1.5 2.5 3.0"
        stdout: "Average: 2.33"
    test3:
      - run: g++ average.cpp -o average && ./average
        stdin: "2.5 3.7 4.1"
        stdout: "Average: 3.43"
    
submit50:
  files: *check50_files
  checks:
    - test1
    - test2
    - test3
  message: "Submit your average.cpp file to check50."

